version: "3"
services:
  dcms-mysql2:
    image: mysql:5.6
    container_name: dev_mysql_dcms2
    ports:
      - 3301:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: dcms
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data5.6:/var/lib/mysql
    networks:
      - default

  dcms-www2:
    build: ./
#    command: bash -c "cd /app && php -S 0.0.0.0:8005"
    container_name: dev_www_dcms2
    links:
      - dcms-mysql2
    ports:
      - "8006:80"
    volumes:
      - ./www:/var/www/html/public

  dcms-phpmyadmindcms:
    image: phpmyadmin/phpmyadmin
    links:
      - dcms-mysql2
    ports:
      - 8003:80
    environment:
      PMA_HOST: dcms-mysql2
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      MYSQL_PORT: 3302
